#!/usr/bin/env osascript
# Returns the current playing song in Spotify for OSX

tell application "Spotify"
  if it is running then
    if player state is playing then
      set track_name to name of current track
      set artist_name to artist of current track
      set song_display to " " & track_name & " - " & artist_name & " "
      if length of song_display is less than 25 then
        set song_display to song_display
      else
        set song_display to text 1 through 20 of song_display & "... "
      end if
      return song_display
    end if
  end if
end tell
